---
title: README files
---

**README files** [give useful information about files in a folder](https://en.wikipedia.org/wiki/README). READMEs are text files (usually `.txt` or `.md`) so that they can be read without any special software. By convention, they are named with uppercase "README" to draw attention to themselves when a folder is opened. If present, READMEs should be the first thing you consult when (re-)opening a project!

When populating a README, think about what someone new to your folder would need to know to use it or build upon it. For instance, when you realize there's something finicky or manual about using your files that you don't have time to fix, at least document it in a README!

## What to include

You can (and should!) include a README anywhere you need to document something, such as:

-   the purpose of the files in a folder
-   how to use the files in a folder
-   special notes about installing software to run code in the folder
-   information about data in the folder, including where, how, and when it was last retrieved
