project:
  type: website

website:
  title: "Best practices for scientific software development"

  navbar:
    search: true
  
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - text: "Introduction"
        href: index.qmd
      - section: "Day-to-day coding"
        href: day-to-day/index.qmd
        contents:
          - day-to-day/IDEs.qmd
          - day-to-day/readmes.qmd
          - day-to-day/commenting.qmd
          - day-to-day/functions.qmd
      - section: "Projects"
        href: projects/index.qmd
        contents:
          - projects/version-control.qmd
          - projects/readmes.qmd
          - projects/virtual-environments.qmd
          - projects/consistency.qmd
          - projects/pipelines.qmd
      - section: "Package development"
        href: package-development/index.qmd
        contents:
          - package-development/readmes.qmd
          - package-development/get-started.qmd
          - package-development/function-docs.qmd
          - package-development/unit-testing.qmd
          - deployment-and-maintenance/developer-docs.qmd
      - section: "Deployment and maintenance"
        href: deployment-and-maintenance/index.qmd
        contents:
          - deployment-and-maintenance/licenses.qmd
          - deployment-and-maintenance/versioning.qmd
          - deployment-and-maintenance/continuous-integration.qmd
          - deployment-and-maintenance/code-review.qmd
      - section: "Extras"
        href: extras/index.qmd
        contents:
          - extras/install-git.qmd
          - extras/writing-commit-messages.qmd
          - extras/admin-git-groups.qmd
          - extras/githubflow-demo-cli.qmd
          - extras/pipenv.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
