project:
  type: website

website:
  title: "Best practices for scientific software development"

  navbar:
    search: true
  
  sidebar:
    style: floating
    collapse-level: 1
    contents:
      - text: "Introduction"
        icon: fast-forward-fill
        href: index.qmd
      - text: "---"
      - section: "Day-to-day coding"
        icon: 1-circle-fill
        href: day-to-day/index.qmd
        contents:
          - day-to-day/IDEs.qmd
          - day-to-day/readmes.qmd
          - day-to-day/commenting.qmd
          - day-to-day/functions.qmd
      - section: "Projects"
        icon: 2-circle-fill
        href: projects/index.qmd
        contents:
          - projects/version-control.qmd
          - projects/readmes.qmd
          - projects/virtual-environments.qmd
          - projects/consistency.qmd
          - projects/pipelines.qmd
      - section: "Package development"
        icon: 3-circle-fill
        href: package-development/index.qmd
        contents:
          - package-development/readmes.qmd
          - package-development/get-started.qmd
          - package-development/function-docs.qmd
          - package-development/unit-testing.qmd
          - package-development/developer-docs.qmd
      - section: "Deployment and maintenance"
        icon: 4-circle-fill
        href: deployment-and-maintenance/index.qmd
        contents:
          - deployment-and-maintenance/licenses.qmd
          - deployment-and-maintenance/versioning.qmd
          - deployment-and-maintenance/continuous-integration.qmd
          - deployment-and-maintenance/code-review.qmd
      - section: "Extras"
        icon: stars
        href: extras/index.qmd
        contents:
          - extras/install-git.qmd
          - extras/writing-commit-messages.qmd
          - extras/admin-git-groups.qmd
          - extras/githubflow-demo-cli.qmd
          - extras/pipenv.qmd
      - text: "---"
      - text: "View on GitHub"
        icon: github
        href: https://github.com/phac-modelling-hub/dev-practices
      - text: "Make a suggestion"
        icon: lightbulb-fill
        href: https://github.com/phac-modelling-hub/dev-practices/issues/new/choose
      - text: "Report an issue"
        icon: bug-fill
        href: https://github.com/phac-modelling-hub/dev-practices/issues/new/choose

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
