---
title: Continuous integration
---

Continuous integration (CI) is the process of continually merging different feature branches into the `main` branch[^1] and automatically triggering software tests[^2] or the overall software build process to help ensure software stability during the development process. CI provides continual feedback on potential issues that may have been introduced during development of new features so they can be addressed before a merge into `main`. For more information about this process, you can read overviews from [Atlassian][atlassian-ci] or [Wikipedia][wikipedia-ci]. 

Continuous integration is often paired with the [code review process](code-review.qmd), where software integration test suites are run during a pull-request/merge request, and the reviewer will only sign-off on merging code into the `main` branch on successful execution of the test suite.

Both GitHub and GitLab provide the capability of triggering tests (or other code) during the initiation of a pull-request and informing reviewers if these tests have passed or failed as part of the pull-request/merge-request. This is accomplished via [GitHub Actions](#github-actions) and [GitLab Pipelines](#gitlab-pipelines).

# GitHub Actions

[GitHub Actions][github-actions] is GitHub's method for triggering code (including software test suites) under a variety of condutions, such as initiation of a pull-request. In general, GitHub Actions are controlled by YAML-formatted files under the `.github/` directory in your git repository.

## Triggering test suites in GitHub

Depending on the programming language you are developing with, there may already be templates and guides on how to setup GitHub actions for running test suites. There are existing repositories for [R](https://github.com/r-lib/actions) actions and a guide for [Python][python-github-actions] actions.

# GitLab Pipelines

[GitLab CI/CD][gitlab-ci] provides a similar service as GitHub Actions for GitLab. That is, GitLab CI/CD can be used to trigger commands to run under different conditions (such as creating a merge-request), which can be used to run software test suites. The results of these test suites are shown within a merge-request to indicate to a reviewer if the updated code passes all the necessary tests.

In general, the execution of GitLab CI/CD commands is configured via a `.gitlab-ci.yml` file within your git repository specifying the commands to run. This defines different [GitLab Pipelines][gitlab-pipelines] to run, which consist of collections of **jobs** to run during different **stages**. These are run using **runners** in GitLab. Please see the [GitLab CI/CD][gitlab-ci] documentation for details on terminology.

[atlassian-ci]: https://www.atlassian.com/continuous-delivery/continuous-integration
[wikipedia-ci]: https://en.wikipedia.org/wiki/Continuous_integration
[github-actions]: https://docs.github.com/en/actions
[python-github-actions]: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
[codeql-actions]: https://docs.github.com/en/code-security/getting-started/securing-your-repository#configuring-code-scanning
[gitlab-ci]: https://docs.gitlab.com/ee/ci/index.html
[gitlab-pipelines]: https://docs.gitlab.com/ee/ci/pipelines/

[^1]: This technique builds upon [branching](../projects/version-control.qmd#branching) and our [recommended git workflow](../projects/version-control.qmd#git-workflow).
[^2]: Like [unit tests](../package-development/unit-testing.qmd)